apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host:  
    http:
      paths:
      - path: /web1/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: web1
            port:
              number: 8081
      - path: /web2/.*
        pathType: ImplementationSpecific
        backend:
          service:
            name: web2
            port:
              number: 8082
