apiVersion: v1
data:
  web1.conf: "server {\n  listen   1111;\n\n  root /var/www/public;\n  index index.html
    index.htm;\n\n  server_name _;\n  \n  location / {\n
    \  try_files $uri.html $uri $uri/ /index.html;\n  }\n}\n"
kind: ConfigMap
metadata:
  name: web1-config
