apiVersion: v1
data:
  web2.conf: "server {\n  listen   2222;\n\n  root /var/www/public;\n  index index.html
    index.htm;\n\n  server_name web2.com;\n  \n  location / {\n   default_type \"text/html\";\n
    \  try_files $uri.html $uri $uri/ /index.html;\n  }\n}\n"
kind: ConfigMap
metadata:
  name: web2-config
